ALTER TABLE history
ADD COLUMN buyer UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE history
ADD CONSTRAINT fk_another_user
FOREIGN KEY (user_id)
REFERENCES users(id) ON DELETE CASCADE;

